name: capiamo_app
description: A professional, secure Flutter app for sharing situas around you.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.9.0
  go_router: ^14.2.7
  flutter_facebook_auth: ^6.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
